### ISSUE TITLE
Style block is removed when running Prefixr

### ISSUE THREAD

**Issue by andreasbovens** [wbond/sublime_prefixr#1]
I did a fresh install of Prefixr (Sublime Text 2, build 2139 on Mac), but it appears to remove the entire block of CSS instead of adding the required prefixes.

**Comment by wbond** [comment]
Can you confirm that this does not happen when pasting the block of CSS into the prefixr web interface (http://prefixr.com/)? If it does not happen there, please provide the CSS you are having trouble with.

**Comment by andreasbovens** [comment]
A restart solved the issue, it seems :-)
