### ISSUE TITLE
Prefixr not listed for install

### ISSUE THREAD

**Issue by ricardozea** [wbond/sublime_prefixr#12]
Hello,

Not sure if it's me or something with Prefixr, but Prefixr is not appearing in the list of plugins to install.

Check the following screenshot: http://d.pr/i/yAkM

Any idea why is this happening?

Thanks.

**Comment by gryphon14** [comment]
I'm also having the same issue.

Perhaps that's because I'm using trial version?

**Comment by ricardozea** [comment]
I don't think there are any restrictions in ST2 when you haven't purchased a license. At least I didn't read anything like that in ST2's documentation.

Besides, the fact that Prefixr is not listed then it wouldn't be a ST2 issue, it would be more a Package Control issue, but that's IF there weren't any issues with Prefixr itself.

However, Prefixr is now showing correctly for me via Package Control:

![prefixr-displays-in-package-control-now-12-17-12](https://f.cloud.github.com/assets/1656481/17585/d6a8931a-487e-11e2-9751-cb0d8f8d2176.png)

Therefore this issue can be closed now.
