### ISSUE TITLE
When running prefixr on a CSS block that already contains some vendor styles, styles before the prefixr'd styles are lost

### ISSUE THREAD

**Issue by omgmog** [wbond/sublime_prefixr#2]
Take the following snippet for example, I've already got my -webkit vendor prefix and the normal w3c, but would like Prefixr to get me the -moz vendor prefix:

```
header form#search input{
    width: 165px;
    height: 22px;
    padding: 0 5px 0 27px;
    margin: 0;
    -webkit-border-radius: 4px 0 0 4px;
    border-radius: 4px 0 0 4px;
    float: left;
    background: url(spyglass.png) 5px 4px no-repeat;
}
```

When I run Prefixr I get the following back:

```
header form#search input{
    -webkit-border-radius: 4px 0 0 4px;
    -moz-border-radius: 4px 0 0 4px;
    border-radius: 4px 0 0 4px;
    float: left;
    background: url(spyglass.png) 5px 4px no-repeat;
}
```

I've now mysteriously lost my width/height/padding/margin styles (all styles before the prefixr'd styles).

If I run the same snippet on prefixr.com I get the following back:

```
header form#search input {
    width: 165px;
    height: 22px;
    padding: 0 5px 0 27px;
    margin: 0;

    -webkit-border-radius: 4px 0 0 4px;
    -moz-border-radius: 4px 0 0 4px;
    border-radius: 4px 0 0 4px;
    float: left;
    background: url(spyglass.png) 5px 4px no-repeat;
}
```

**Comment by omgmog** [comment]
I've just noticed this might be a duplication of Issue 1

**Comment by wbond** [comment]
So Sublime Prefixr doesn't send the whole rule, just the innards of it, in an attempt to handle the whitespace seamlessly with the existing document. It appears there is a bug in Prefixr. I've send a notice to Jeffrey about it. 

You can replicate it by pasting the following into Prefixr:

``` css
width: 165px;
height: 22px;
padding: 0 5px 0 27px;
margin: 0;
-webkit-border-radius: 4px 0 0 4px;
border-radius: 4px 0 0 4px;
float: left;
background: url(spyglass.png) 5px 4px no-repeat;
```

**Comment by ktilcu** [comment]
Any word on this?

**Comment by ghost** [comment]
This is a serious problem.

**Comment by jakelodwick** [comment]
@duydangle Agreed - for me, it's the difference between using the package, and not using it.
It's a shame; sublime_prefixr has real potential to accelerate my development.
