### ISSUE TITLE
doesn't work for 'border-radius' :( 

### ISSUE THREAD

**Issue by athimannil** [wbond/sublime_prefixr#20]
I really like the prefixr unfortunately the border-radius doesn't work for me on mac(I didn't test on windows)

BEFORE:-
                #patient02 #filmstrip .box img{
                    display: block !important;
                    margin-top: 8px;
                    border: 1px solid #CCC;
                    border-radius: 6px;
                    box-shadow:0 0 5px black;
                }

AFTER:-
                #patient02 #filmstrip .box img{
                    display: block !important;
                    margin-top: 8px;
                    border: 1px solid #CCC;
                    border-radius: 6px;
                    -webkit-box-shadow:0 0 5px black;
                    box-shadow:0 0 5px black;
                }

Please reply me If anybody know the solution :)

**Comment by ivansammartino** [comment]
+1, me too in Windows

**Comment by igrossiter** [comment]
+1 for linux

**Comment by wbond** [comment]
To my knowledge this is an issue with the prefixr.com API and not something that can be fixed in the Sublime plugin.
