### ISSUE TITLE
Only partial prefixes written with box-shadow

### ISSUE THREAD

**Issue by ivansammartino** [wbond/sublime_prefixr#24]
Hello, when running Prefixr on "box-shadow" property, it only adds the -webkit prefix but not the -moz one

input:
a {
    box-shadow:0 0 5px black;
}

output:
a {
    -webkit-box-shadow:0 0 5px black;
    box-shadow:0 0 5px black;
}

The bottom bar reports: "The property -moz-box-shadow is compatible with -webkit-box-shadow and should be included as well"

Please any help? Thanks

**Comment by wbond** [comment]
This sounds like an issue with the prefixr.com API and not the Sublime plugin. All this plugin does is post your CSS to prefixr.com and fetch the result.
