### ISSUE TITLE
old property for opacity in IE

### ISSUE THREAD

**Issue by pustovalov** [wbond/sublime_prefixr#9]
Hello, this property:
-ms-filter: "progid: DXImageTransform.Microsoft.Alpha (Opacity = 100)";
no longer needed for IE.
As it is written on this site http://css3please.com/
filter: alpha (opacity = 90); / \* IE6-IE8 \* /

**Comment by wbond** [comment]
Please send such bug reports to prefixr.com. This plugin simply retrieves results from there.
